### ISSUE TITLE
Docs for private repos suggest the wrong variable key for SSH key access.

### ISSUE THREAD

**Issue by mp998** [appvia/terranetes#150]
The documentation recommends creating a secret with a key of `SSH_KEY_AUTH`. I found that that key doesn't work. I had to dig into the code for the controller to find that it is looking for a key of `SSH_AUTH_KEY`

This line in the docs needs to be updated to use the right variable:
https://github.com/appvia/terranetes/blob/c9ef5e2f52030d5dfbfc26e82b829fd0ba60116b/docs/terranetes-controller/developer/private.md?plain=1#L17

**Comment by KashifSaadat** [comment]
Good spot, thanks @mp998! I've corrected this in #152.
